# Generated by Django 3.2.17 on 2023-08-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osf', '0015_osfuser_allow_indexing'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractprovider',
            name='assertions_enabled',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='abstractprovider',
            name='supported_citation_styles',
            field=models.ManyToManyField(related_name='supporting_providers', to='osf.CitationStyle'),
        ),
    ]
